### ISSUE TITLE
Problem in generating point clouds from predicted Depth

### ISSUE THREAD

**Issue by hmishra2250** [HKUST-Aerial-Robotics/MVDepthNet#7]
Thanks a lot for open-sourcing your project!

The most impressive thing, that catches most people is that the paper claims to be better than DeMoN. The heat map looks very good. However, when I try reconstructing the 3D point cloud from the depth, the result looks uneven, wavy and also it doesn't preserve the shape of the objects.

Shown below are the point clouds obtained from MVDepthNet and Demon.

MVDepth Pointcloud:

![screenshot from 2018-09-27 19-08-47](https://user-images.githubusercontent.com/9528717/46153729-56605380-c291-11e8-86ed-c0b840e994e5.png)
![screenshot from 2018-09-27 19-57-56](https://user-images.githubusercontent.com/9528717/46153750-6415d900-c291-11e8-887f-8791dc462136.png)

DeMoN pointcloud:

![screenshot from 2018-09-27 20-00-03](https://user-images.githubusercontent.com/9528717/46153780-6d9f4100-c291-11e8-95a8-b32742eeb072.png)

As shown above, DeMoN point cloud preserves the object structure.

Is it the problem with the model, or there is something done wrongly by me. I can provide the corresponding images and pose if required for you to verify.

Also, the pretrained model provided along with the repo is the one trained with or without Geometric Augmentation.

Any suggestions/ideas are highly appreciated! :)

**Comment by WANG-KX** [comment]
Dear,

Thanks for your interest in the project.
Would you please provide the image pair and the pose of the test?
The model is trained with Geometric Augmentation.

In some cases, yes, the result is not as good as that of DeMoN. As our method estimates the depth using information from multiview observation. DeMoN, on the other hand, can estimate the depth with **zero baseline** meaning that it can use **semantic information** such as flat surfaces etc. Maybe it is the reason that the point cloud from DeMoN is visually better than ours, especially when it comes to **small baselines**.

Regards,
Kaixuan

**Comment by hmishra2250** [comment]
Hi Kaixuan,

Thanks for the super quick reply. [Here](https://drive.google.com/drive/folders/1jmfXPMDV7san8VpJfhIrOrIx4RWSAiyV?usp=sharing) are the images and the pose you asked for. 

The thing is, I tried generating point clouds for the images in sample_data.pkl and I was getting similar bad results. I don't understand how can MVDepthNet be performing better than DeMoN and yet giving worse reconstructions. Is it some problem with the way I handle MVDepthNet or am I missing something?

**Comment by WANG-KX** [comment]
Dear,

The tested image you use is from TUM RGBD Dataset, and I am not sure if it is included in the training set of DeMoN. As I mentioned in the paper, images from TUM RGBD Dataset are split differently in MVDepthNet and in DeMoN (and it is the reason that we did not compare the results on TUM RGBD dataset in the paper). If you would like to compare, please make sure that it is not used to train both of the networks.

Here I provide the first ten images of SceneNN Dataset. It is not manually selected so that we are better than DeMoN. 
The top row of each result is left image, right image, RGBD camera depth map, the MVDepthNet generated depth map, error map.
The second row of each result is RGBD camera depth map, the DeMoN generated depth map, its error map.
![delete](https://user-images.githubusercontent.com/21083590/46204493-03010a80-c350-11e8-80de-da61744a8502.jpg)

 As I tested the DeMoN, it can generate very smooth point clouds. However, in some cases, the scale is not consistent with each pixel. It's ok to have wrong scale estimation of DeMoN, but the scale should be consistent. DeMoN is an impressive project that it also estimates camera poses. Given camera poses, I won't be surprised that MVDepthNet is better than DeMoN when evaluating the depth maps.

Regards,
Kaixuan

**Comment by hmishra2250** [comment]
Thanks for the information Kaixuan. 

I think I get it now. Since we don't know the dataset split of TUM RGBD, we shouldn't rely on its evaluation.

And yes, the scale is one problem with DeMoN. All the point clouds are in their own scale. Let's say, I can solve the scale problem by some point cloud registration method. Then, what are your views on comparing just the quality of depth from DeMoN vs that from MVDepthNet?

Also, it would be a great help if you can share those 10 image pair, pose and camera intrinsics. (Downloading whole SceneNN dataset is hard, it's too large).

I thank you very much for helping with my queries.

Regards
Himadri

**Comment by WANG-KX** [comment]
Dear,

You can download the bag at [link](https://www.dropbox.com/s/rgawq1wh4p4sgrw/github_issue.pkl?dl=0). The data format is not the same as the data provided as the example. Please convert the data yourself.

The link will be valid for a week.

Regards,
Kaixuan
